### ISSUE TITLE
Documentation Issue / name conflict

### ISSUE THREAD

**Issue by mardiros** [njarvis/pyshop#1]
* pyshop version: *
* Python version: *
* Operating System: *

### Description

The installation Guide Install another Pyshop Project. [Mine in fact](https://github.com/mardiros/pyshop)

Take a look on pypi: https://pypi.python.org/pypi/pyshop

Do what you want, but I suggest you to rename your project.

### What I Did

I read `http://pyshop.readthedocs.io/en/latest/installation.html#stable-release`

**Comment by njarvis** [comment]
So the issue is with the readthedocs.io URL?  You would like to publish your documentation under http://pyshop.readthedocs.io/ ?

I would have no problem renaming the readthedocs.io URL for my package.

**Comment by mardiros** [comment]
It could be sweet if I can get the readthedocs url.

I was referring an error **IN** your documentation.

![image](https://user-images.githubusercontent.com/447396/37405268-7e4c37f8-2794-11e8-81c4-8a37e6c802a5.png)


`pip install pyshop` will install the [my private repository for python packages named PyShop](https://pypi.python.org/pypi/pyshop)

**Comment by njarvis** [comment]
Ah, I understand!   Will update my (local) documentation. 

As this really is a personal "play" project, I've deleted the corresponding readthedocs page.  The URL should/will be free for you to use on your project.  Hope this helps.

**Comment by mardiros** [comment]
Thanks!
